<?php

return [
    'db' => [
        'host' => '127.0.0.1',
        'user' => 'adlink',
        'pass' => 'adlink',
        'name' => 'adlink',
        'port' => 3306,
    ],
    'geo' => [
        'allowed_regions' => [
            'MOW',
            'SPE',
            'NIZ',
            'SVE',
            'KDA',
            'TAT',
            'ROS',
            'SAM',
            'KGD',
            'KHA',
            'PER',
            'VLA',
            'KEM',
            'KIR',
            'KRS',
            'IRK',
            'KLU',
            'TVE',
            'VOR',
            'LEN',
            'OMS',
            'ALR',
            'YAN',
            'CHE',
            'BEL',
            'BRY',
            'TUL',
            'SAR',
            'VOL',
            'ORL',
            'PNZ',
            'KHM',
            'TYU',
            'KOS',
            'SVE',
            'ALT',
            'KYA',
            'KAM',
            'SAK',
            'MSK',
            'IVA',
        ],
    ],
    'fraud' => [
        'max_clicks_per_ip_campaign_10min' => 5,
    ],
];
